language: go

go:
  - 1.9

install:
  - go get github.com/prometheus/client_golang/prometheus
  - go get golang.org/x/crypto/acme/autocert

script:
  # build test for supported platforms
  - GOOS=linux go build
  - GOOS=darwin go build
  - GOOS=freebsd go build
  - GOARCH=386 go build

  # run tests on a standard platform
  - go test -race -v ./...